/*
 * Copyright 2021 Delft University of Technology
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package server;

import java.util.List;
import java.util.Random;
import java.util.Set;

import commons.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import server.database.IngredientRepository;
import server.database.RecipeIngredientRepository;
import server.database.RecipeRepository;

@Configuration
public class Config {

    @Value("${db.mode:large}")
    private String dbMode;

    @Bean
    public Random getRandom() {
        return new Random();
    }

    /**
     * Seeds the database based on the configured mode.
     * Can be controlled via --db.mode=large|small|empty command line argument.
     * Defaults to 'large' if not specified.
     */
    @Bean
    public CommandLineRunner demoData(RecipeRepository recipeRepo,
                                      IngredientRepository ingredientRepo,
                                      RecipeIngredientRepository recipeIngredientRepo) {
        return args -> {
            System.out.println();
            System.out.println("Database seeding mode: " + dbMode);
            System.out.println();

            if (dbMode.equals("empty")) {
                System.out.println("Empty mode: no data loaded in the server.");
                return;
            }

            if (dbMode.equals("small")) {
                seedSmallDataset(recipeRepo, ingredientRepo, recipeIngredientRepo);
            } else if (dbMode.equals("large")) {
                seedLargeDataset(recipeRepo, ingredientRepo, recipeIngredientRepo);
            } else {
                System.out.println("Seeding variant does not exist. Defaulting to large.");
                seedLargeDataset(recipeRepo, ingredientRepo, recipeIngredientRepo);
            }

            System.out.println("Database startup was successful.");
        };
    }

    /**
     * Generated by chatgpt
     * Seeds a small dataset (3 recipes, 6 ingredients).
     */
    private void seedSmallDataset(RecipeRepository recipeRepo,
                                   IngredientRepository ingredientRepo,
                                   RecipeIngredientRepository recipeIngredientRepo) {
        System.out.println("Loading small dataset...");

        // 1. Create Ingredients
        Ingredient flour = ingredientRepo.save(new Ingredient("Flour",
                1.0, 10.0, 76.0,IngredientCategory.PANTRY, Set.of(Allergen.GLUTEN)));
        Ingredient sugar = ingredientRepo.save(new Ingredient("Sugar",
                0.0, 0.0, 100.0, IngredientCategory.PANTRY,Set.of()));
        Ingredient egg = ingredientRepo.save(new Ingredient("Egg",
                11.0, 13.0, 1.1, IngredientCategory.DAIRY,Set.of(Allergen.EGGS)));
        Ingredient tomato = ingredientRepo.save(new Ingredient("Tomato",
                0.2, 0.9, 3.9, IngredientCategory.VEGETABLES, Set.of()));
        Ingredient bread = ingredientRepo.save(new Ingredient("Bread",
                3.2, 9.0, 49.0, IngredientCategory.BAKERY,Set.of(Allergen.GLUTEN)));
        Ingredient cheese = ingredientRepo.save(new Ingredient("Cheese",
                25.0, 25.0, 1.3, IngredientCategory.DAIRY,Set.of(Allergen.MILK)));

        // 2. Create Recipes
        Recipe pancake = recipeRepo.save(new Recipe("Pancakes", 4,
                List.of("Mix ingredients", "Fry in pan",
                        "Serve hot"), Language.English, true, true, false));
        Recipe tomatoSoup = recipeRepo.save(new Recipe("Tomato Soup", 2,
                List.of("Boil Water", "Add Tomato"), Language.English, true, true, true));
        Recipe grilledCheese = recipeRepo.save(new Recipe("Grilled Cheese", 1,
                List.of("Toast Bread", "Melt Cheese"), Language.English, true, true, false));

        // 3. Create RecipeIngredients for Pancakes
        recipeIngredientRepo.save(new RecipeIngredient(pancake,
                flour, null, 200.0, Unit.GRAM));
        recipeIngredientRepo.save(new RecipeIngredient(pancake,
                sugar, null, 50.0, Unit.GRAM));
        recipeIngredientRepo.save(new RecipeIngredient(pancake,
                egg, null, 2.0, Unit.CUSTOM));

        // 4. Create RecipeIngredients for Tomato Soup
        recipeIngredientRepo.save(new RecipeIngredient(tomatoSoup,
                tomato, null, 500.0, Unit.GRAM));

        // 5. Create RecipeIngredients for Grilled Cheese
        recipeIngredientRepo.save(new RecipeIngredient(grilledCheese,
                bread, null, 2.0, Unit.CUSTOM));
        recipeIngredientRepo.save(new RecipeIngredient(grilledCheese,
                cheese, null, 100.0, Unit.GRAM));
    }

    /**
     * Seeds a large dataset (20+ recipes, 30+ ingredients).
     * Generated by ChatGPT and split into smaller methods to comply with Checkstyle rules.
     */
    private void seedLargeDataset(RecipeRepository recipeRepo,
                                   IngredientRepository ingredientRepo,
                                   RecipeIngredientRepository recipeIngredientRepo) {
        System.out.println("Loading large dataset...");

        Ingredient[] ingredients = seedLargeIngredients(ingredientRepo);
        Recipe[] recipes = seedLargeRecipes(recipeRepo);
        linkLargeRecipeIngredients(recipeIngredientRepo, recipes, ingredients);
    }

    /**
     * Creates all ingredients for the large dataset.
     * Generated by ChatGPT, shortened for Checkstyle compliance.
     *
     * @param ingredientRepo the ingredient repository
     * @return array of created ingredients
     */
    private Ingredient[] seedLargeIngredients(IngredientRepository ingredientRepo) {
        Ingredient[] ingredients = new Ingredient[30];
        ingredients[0] = ingredientRepo.save(new Ingredient("Flour",
                10.0, 1.0, 76.0, IngredientCategory.PANTRY, Set.of(Allergen.GLUTEN)));
        ingredients[1] = ingredientRepo.save(new Ingredient("Sugar",
                0.0, 0.0, 100.0, IngredientCategory.PANTRY, Set.of()));
        ingredients[2] = ingredientRepo.save(new Ingredient("Egg",
                13.0, 11.0, 1.1, IngredientCategory.DAIRY,Set.of(Allergen.EGGS)));
        ingredients[3] = ingredientRepo.save(new Ingredient("Tomato",
                0.9, 0.2, 3.9, IngredientCategory.VEGETABLES, Set.of()));
        ingredients[4] = ingredientRepo.save(new Ingredient("Bread",
                9.0, 3.2, 49.0, IngredientCategory.BAKERY, Set.of(Allergen.GLUTEN)));
        ingredients[5] = ingredientRepo.save(new Ingredient("Cheese",
                25.0, 33.0, 1.3, IngredientCategory.DAIRY, Set.of(Allergen.MILK)));
        ingredients[6] = ingredientRepo.save(new Ingredient("Milk",
                3.4, 1.0, 5.0, IngredientCategory.DAIRY, Set.of(Allergen.MILK)));
        ingredients[7] = ingredientRepo.save(new Ingredient("Butter",
                0.9, 81.0, 0.1, IngredientCategory.DAIRY, Set.of(Allergen.MILK)));
        ingredients[8] = ingredientRepo.save(new Ingredient("Salt",
                0.0, 0.0, 0.0, IngredientCategory.SPICES, Set.of()));
        ingredients[9] = ingredientRepo.save(new Ingredient("Pepper",
                11.0, 3.3, 64.0, IngredientCategory.SPICES, Set.of()));
        ingredients[10] = ingredientRepo.save(new Ingredient("Chicken",
                31.0, 3.6, 0.0, IngredientCategory.MEAT, Set.of()));
        ingredients[11] = ingredientRepo.save(new Ingredient("Beef",
                26.0, 15.0, 0.0, IngredientCategory.MEAT, Set.of()));
        ingredients[12] = ingredientRepo.save(new Ingredient("Pasta",
                13.0, 1.5, 75.0, IngredientCategory.PANTRY, Set.of(Allergen.GLUTEN)));
        ingredients[13] = ingredientRepo.save(new Ingredient("Rice",
                2.7, 0.3, 28.0, IngredientCategory.PANTRY, Set.of()));
        ingredients[14] = ingredientRepo.save(new Ingredient("Potato",
                2.0, 0.1, 17.0, IngredientCategory.VEGETABLES, Set.of()));
        ingredients[15] = ingredientRepo.save(new Ingredient("Onion",
                1.1, 0.1, 9.3, IngredientCategory.VEGETABLES, Set.of()));
        ingredients[16] = ingredientRepo.save(new Ingredient("Garlic",
                6.4, 0.5, 33.0, IngredientCategory.VEGETABLES, Set.of()));
        ingredients[17] = ingredientRepo.save(new Ingredient("Carrot",
                0.9, 0.2, 10.0, IngredientCategory.VEGETABLES, Set.of()));
        ingredients[18] = ingredientRepo.save(new Ingredient("Lettuce",
                1.4, 0.2, 2.9, IngredientCategory.VEGETABLES, Set.of()));
        ingredients[19] = ingredientRepo.save(new Ingredient("Cucumber"
                , 0.7, 0.1, 3.6, IngredientCategory.VEGETABLES, Set.of()));
        ingredients[20] = ingredientRepo.save(new Ingredient("Olive Oil",
                0.0, 100.0, 0.0, IngredientCategory.PANTRY, Set.of()));
        ingredients[21] = ingredientRepo.save(new Ingredient("Lemon",
                1.1, 0.3, 9.3, IngredientCategory.FRUIT, Set.of()));
        ingredients[22] = ingredientRepo.save(new Ingredient("Chocolate",
                7.5, 30.0, 59.0, IngredientCategory.PANTRY, Set.of(Allergen.MILK, Allergen.SOY)));
        ingredients[23] = ingredientRepo.save(new Ingredient("Vanilla Extract",
                0.0, 0.0, 13.0, IngredientCategory.SPICES, Set.of()));
        ingredients[24] = ingredientRepo.save(new Ingredient("Bacon",
                37.0, 42.0, 1.4, IngredientCategory.MEAT, Set.of()));
        ingredients[25] = ingredientRepo.save(new Ingredient("Mushroom",
                3.1, 0.3, 3.3, IngredientCategory.VEGETABLES, Set.of()));
        ingredients[26] = ingredientRepo.save(new Ingredient("Spinach",
                2.9, 0.4, 3.6, IngredientCategory.VEGETABLES, Set.of()));
        ingredients[27] = ingredientRepo.save(new Ingredient("Tuna",
                30.0, 1.0, 0.0, IngredientCategory.FISH, Set.of(Allergen.FISH)));
        ingredients[28] = ingredientRepo.save(new Ingredient("Soy Sauce",
                8.1, 0.0, 4.9, IngredientCategory.CONDIMENTS,
                Set.of(Allergen.SOY, Allergen.GLUTEN)));
        ingredients[29] = ingredientRepo.save(new Ingredient("Ginger",
                1.8, 0.8, 18.0, IngredientCategory.SPICES, Set.of()));
        return ingredients;
    }

    /**
     * Creates all recipes for the large dataset.
     * Generated by ChatGPT, shortened for Checkstyle compliance.
     *
     * @param recipeRepo the recipe repository
     * @return array of created recipes
     */
    private Recipe[] seedLargeRecipes(RecipeRepository recipeRepo) {
        Recipe[] recipes = new Recipe[20];
        recipes[0] = recipeRepo.save(new Recipe("Pancakes", 4,
                List.of("Mix ingredients", "Fry in pan",
                        "Serve hot"), Language.English, true, true, false));
        recipes[1] = recipeRepo.save(new Recipe("Tomato soup", 2,
                List.of("Boil Water", "Add Tomato"), Language.English, true, true, true));
        recipes[2] = recipeRepo.save(new Recipe("Grilled cheese", 1,
                List.of("Toast Bread", "Melt Cheese"), Language.English, true, true, false));
        recipes[3] = recipeRepo.save(new Recipe("Caesar salad", 2,
                List.of("Chop lettuce", "Add dressing",
                        "Top with croutons"), Language.English, false, true, false));
        recipes[4] = recipeRepo.save(new Recipe("Spaghetti carbonara", 4,
                List.of("Boil pasta", "Fry bacon", "Mix with eggs and cheese",
                        "Combine and serve"), Language.English, false, false, false));
        recipes[5] = recipeRepo.save(new Recipe("Chicken stir fry", 3,
                List.of("Cut chicken", "Heat oil in wok", "Stir fry chicken and vegetables",
                        "Add soy sauce"), Language.English, false, true, false));
        recipes[6] = recipeRepo.save(new Recipe("Beef stew", 6,
                List.of("Brown beef", "Add vegetables", "Add broth",
                        "Simmer for 2 hours"), Language.English, false, false, false));
        recipes[7] = recipeRepo.save(new Recipe("Mashed potatoes", 4,
                List.of("Boil potatoes", "Mash with butter and milk",
                        "Season with salt and pepper"), Language.English, true, true, false));
        recipes[8] = recipeRepo.save(new Recipe("Chocolate cake", 8,
                List.of("Mix dry ingredients", "Add wet ingredients",
                        "Bake at 180C for 30 minutes"), Language.English, false, false, false));
        recipes[9] = recipeRepo.save(new Recipe("Tuna salad", 2,
                List.of("Mix tuna with mayo", "Add chopped vegetables",
                        "Serve on lettuce"), Language.English, true, true, false));
        recipes[10] = recipeRepo.save(new Recipe("Mushroom risotto", 4,
                List.of("Saute mushrooms", "Add rice", "Gradually add broth",
                        "Stir continuously"), Language.English, false, false, false));
        recipes[11] = recipeRepo.save(new Recipe("Greek salad", 4,
                List.of("Chop vegetables", "Add olives and feta",
                        "Dress with olive oil and lemon"), Language.English, true, true, false));
        recipes[12] = recipeRepo.save(new Recipe("Fried rice", 3,
                List.of("Cook rice", "Fry with vegetables",
                        "Add soy sauce and egg"), Language.English, true, true, false));
        recipes[13] = recipeRepo.save(new Recipe("Eggs benedict", 2,
                List.of("Toast bread", "Poach eggs", "Make hollandaise sauce",
                        "Assemble"), Language.English, false, false, false));
        recipes[14] = recipeRepo.save(new Recipe("French toast", 2,
                List.of("Whisk eggs and milk", "Dip bread",
                        "Fry until golden"), Language.English, true, true, false));
        recipes[15] = recipeRepo.save(new Recipe("Garlic bread", 4,
                List.of("Mix butter with garlic", "Spread on bread",
                        "Bake until crispy"), Language.English, true, true, false));
        recipes[16] = recipeRepo.save(new Recipe("Chicken soup", 6,
                List.of("Boil chicken", "Add vegetables",
                        "Season and simmer"), Language.English, true, false, false));
        recipes[17] = recipeRepo.save(new Recipe("Bacon wrapped chicken", 4,
                List.of("Wrap chicken with bacon", "Season",
                        "Bake at 200C for 25 minutes"), Language.English, false, false, false));
        recipes[18] = recipeRepo.save(new Recipe("Spinach omelette", 1,
                List.of("Beat eggs", "Saute spinach",
                        "Pour eggs and fold"), Language.English, true, true, false));
        recipes[19] = recipeRepo.save(new Recipe("Carrot cake", 10,
                List.of("Grate carrots", "Mix with batter",
                        "Bake at 175C for 40 minutes"), Language.English, false, false, false));
        return recipes;
    }

    /**
     * Links recipes with their ingredients for the large dataset.
     * Generated by ChatGPT, shortened for Checkstyle compliance.
     *
     * @param recipeIngredientRepo the recipe ingredient repository
     * @param recipes array of recipes
     * @param ingredients array of ingredients
     */
    private void linkLargeRecipeIngredients(RecipeIngredientRepository recipeIngredientRepo,
                                             Recipe[] recipes, Ingredient[] ingredients) {
        linkRecipesGroup1(recipeIngredientRepo, recipes, ingredients);
        linkRecipesGroup2(recipeIngredientRepo, recipes, ingredients);
        linkRecipesGroup3(recipeIngredientRepo, recipes, ingredients);
    }

    /**
     * Links first group of recipes with ingredients (recipes 0-6).
     * Generated by ChatGPT, split for Checkstyle compliance.
     */
    private void linkRecipesGroup1(RecipeIngredientRepository repo,
                                     Recipe[] recipes, Ingredient[] ingredients) {
        repo.save(new RecipeIngredient(recipes[0], ingredients[0], null, 200.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[0], ingredients[1], null, 50.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[0], ingredients[2], null, 2.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[0], ingredients[6], null, 0.3, Unit.LITER));

        repo.save(new RecipeIngredient(recipes[1], ingredients[3], null, 500.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[1], ingredients[15], null, 1.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[1], ingredients[16], null, 2.0, Unit.CUSTOM));

        repo.save(new RecipeIngredient(recipes[2], ingredients[4], null, 2.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[2], ingredients[5], null, 100.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[2], ingredients[7], null, 20.0, Unit.GRAM));

        repo.save(new RecipeIngredient(recipes[3], ingredients[18], null, 200.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[3], ingredients[5], null, 50.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[3], ingredients[4], null, 2.0, Unit.CUSTOM));

        repo.save(new RecipeIngredient(recipes[4], ingredients[12], null, 400.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[4], ingredients[24], null, 150.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[4], ingredients[2], null, 4.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[4], ingredients[5], null, 100.0, Unit.GRAM));

        repo.save(new RecipeIngredient(recipes[5], ingredients[10], null, 400.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[5], ingredients[17], null, 100.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[5], ingredients[15], null, 1.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[5], ingredients[28], null, 0.05, Unit.LITER));

        repo.save(new RecipeIngredient(recipes[6], ingredients[11], null, 800.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[6], ingredients[14], null, 400.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[6], ingredients[17], null, 200.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[6], ingredients[15], null, 2.0, Unit.CUSTOM));
    }

    /**
     * Links second group of recipes with ingredients (recipes 7-12).
     * Generated by ChatGPT, split for Checkstyle compliance.
     */
    private void linkRecipesGroup2(RecipeIngredientRepository repo,
                                     Recipe[] recipes, Ingredient[] ingredients) {
        repo.save(new RecipeIngredient(recipes[7], ingredients[14], null, 1000.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[7], ingredients[7], null, 50.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[7], ingredients[6], null, 0.1, Unit.LITER));

        repo.save(new RecipeIngredient(recipes[8], ingredients[0], null, 300.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[8], ingredients[1], null, 250.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[8], ingredients[22], null, 200.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[8], ingredients[2], null, 3.0, Unit.CUSTOM));

        repo.save(new RecipeIngredient(recipes[9], ingredients[27], null, 200.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[9], ingredients[18], null, 100.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[9], ingredients[19], null, 1.0, Unit.CUSTOM));

        repo.save(new RecipeIngredient(recipes[10], ingredients[13], null, 300.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[10], ingredients[25], null, 250.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[10], ingredients[15], null, 1.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[10], ingredients[7], null, 50.0, Unit.GRAM));

        repo.save(new RecipeIngredient(recipes[11], ingredients[3], null, 300.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[11], ingredients[19], null, 2.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[11], ingredients[5], null, 150.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[11], ingredients[20], null, 0.05, Unit.LITER));

        repo.save(new RecipeIngredient(recipes[12], ingredients[13], null, 400.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[12], ingredients[2], null, 2.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[12], ingredients[17], null, 100.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[12], ingredients[28], null, 0.03, Unit.LITER));
    }

    /**
     * Links third group of recipes with ingredients (recipes 13-19).
     * Generated by ChatGPT, split for Checkstyle compliance.
     */
    private void linkRecipesGroup3(RecipeIngredientRepository repo,
                                     Recipe[] recipes, Ingredient[] ingredients) {
        // Remaining recipes with ingredients
        repo.save(new RecipeIngredient(recipes[13], ingredients[2], null, 4.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[13], ingredients[4], null, 4.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[13], ingredients[7], null, 50.0, Unit.GRAM));

        repo.save(new RecipeIngredient(recipes[14], ingredients[4], null, 4.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[14], ingredients[2], null, 3.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[14], ingredients[6], null, 0.1, Unit.LITER));

        repo.save(new RecipeIngredient(recipes[15], ingredients[4], null, 1.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[15], ingredients[7], null, 100.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[15], ingredients[16], null, 5.0, Unit.CUSTOM));

        repo.save(new RecipeIngredient(recipes[16], ingredients[10], null, 500.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[16], ingredients[17], null, 200.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[16], ingredients[15], null, 1.0, Unit.CUSTOM));

        repo.save(new RecipeIngredient(recipes[17], ingredients[10], null, 600.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[17], ingredients[24], null, 200.0, Unit.GRAM));

        repo.save(new RecipeIngredient(recipes[18], ingredients[2], null, 3.0, Unit.CUSTOM));
        repo.save(new RecipeIngredient(recipes[18], ingredients[26], null, 100.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[18], ingredients[5], null, 50.0, Unit.GRAM));

        repo.save(new RecipeIngredient(recipes[19], ingredients[17], null, 300.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[19], ingredients[0], null, 250.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[19], ingredients[1], null, 200.0, Unit.GRAM));
        repo.save(new RecipeIngredient(recipes[19], ingredients[2], null, 3.0, Unit.CUSTOM));
    }
}